name: Keep the major version tag up-to-date

on:
  release:
    types: [published, edited]

jobs:
  update-major-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: Actions-R-Us/actions-tagger@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
